[tool.poetry]
name = "greet"
version = "0.1.0"
description = ""
authors = ["jim Cassidy <jim@ion8>"]
readme = "README.md"

[tool.poetry.scripts]
greet = "greet.main:app"

[tool.poetry.dependencies]
python = "^3.6"
typer = {extras = ["all"], version = "^0.6.1"}

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"